name: Build

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Build
      run: cargo build --release --verbose --all-targets

    - name: Run tests
      run: cargo test --verbose

    - run: cargo run
    - run: cargo run --package rust-intro --example 01_intro
    - run: cargo run --package rust-intro --example 02_variable
    - run: cargo run --package rust-intro --example 03_compand
    - run: cargo run --package rust-intro --example 04_array-tuple
    - run: cargo run --package rust-intro --example 05_vector
    # - run: cargo run --package rust-intro --example 06_functions # stdin
    - run: cargo run --package rust-intro --example 07_ownership
    - run: cargo run --package rust-intro --example 08_immutab_ref
    - run: cargo run --package rust-intro --example 09_condition
    # - run: cargo run --package rust-intro --example 10_loop  # stdin
    - run: cargo run --package rust-intro --example 11_forloop
    - run: cargo run --package rust-intro --example 12_quiz
    - run: cargo run --package rust-intro --example 13_struct
    - run: cargo run --package rust-intro --example 14_trait
    - run: cargo run --package rust-intro --example 15_enum
    - run: cargo run --package rust-intro --example 16_generic
    - run: cargo run --package rust-intro --example 17_optenum
    - run: cargo run --package rust-intro --example 18_result
    - run: cargo run --package rust-intro --example 19_hashmap
    - run: cargo run --package rust-intro --example 20_lifetime
    - run: cargo run --package rust-intro --example 21_closure
    - run: cargo run --package rust-intro --example 22_functypes
    - run: cargo run --package rust-intro --example 23_iterators
    - run: cargo run --package rust-intro --example 24_module
    - run: cargo run --package rust-intro --example 25_smartpointer
    - run: cargo run --package rust-intro --example 26_singlylist
    #- run: cargo run --package rust-intro --example
    #- run: cargo run --package rust-intro --example
    #- run: cargo run --package rust-intro --example
    #- run: cargo run --package rust-intro --example
    #- run: cargo run --package rust-intro --example