name: Build

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

# no need to cache usage,
#    - uses: actions/cache@v3
#      with:
#        path: |
#          ~/.cargo/bin/
#          ~/.cargo/registry/index/
#          ~/.cargo/registry/cache/
#          ~/.cargo/git/db/
#          target/
#        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Build
      run: cargo build --release --verbose --all-targets

    - name: Run tests
      run: cargo test --verbose

    - run: cargo run --package _01_intro
    - run: cargo run --package _02_variable
    - run: cargo run --package _03_compand
    - run: cargo run --package _04_array-tuple
    - run: cargo run --package _05_vector
    - run: echo "33" |  cargo run --package _06_functions # stdin
    - run: cargo run --package _07_ownership
    - run: cargo run --package _08_immutab_ref
    - run: cargo run --package _09_condition
    - run: echo "32" |  cargo run --package _10_loop  # stdin
    - run: cargo run --package _11_forloop
    - run: cargo run --package _12_quiz
    - run: cargo run --package _13_struct
    - run: cargo run --package _14_trait
    - run: cargo run --package _15_enum
    - run: cargo run --package _16_generic
    - run: cargo run --package _17_optenum
    - run: cargo run --package _18_result
    - run: cargo run --package _19_hashmap
    - run: cargo run --package _20_lifetime
    - run: cargo run --package _21_closure
    - run: cargo run --package _22_functypes
    - run: cargo run --package _23_iterators
    - run: cargo run --package _24_module
    - run: cargo run --package _25_smartpointer
    - run: cargo run --package _26_singlylist
    - run: cargo run --package _27_refcounting
    - run: cargo run --package _28_refcell
    - run: cargo run --package _29_doublelinked
    - run: cargo run --package _30_memory_leak
    - run: cargo run --package _31_macro
    - run: echo "21.1" | cargo run --package _32_capturetype
    - run: cargo run --package _33_unittype
    - run: cargo run --package _34_asref
    - run: cargo run --package _35_swap
    - run: cargo run --package _36_questionmark
    - run: cargo run --package _37_testing

    - run: cargo run --package _01_anagram
    - run: cargo run --package _02_popularity
    - run: cargo run --package _03_stockprice


    - run: cargo run --package _01_associated
    - run: cargo run --package _02_iterators
    - run: cargo run --package _03_dispatch
    - run: cargo run --package _04_partial_order
    - run: cargo run --package _05_struct_init
    - run: cargo run --package _06_consts
    - run: cargo run --package _07_thread
    - run: cargo run --package _08_channels
    - run: cargo run --package _09_concurrency
    #- run: cargo run --package
    #- run: cargo run --package
    #- run: cargo run --package
    #- run: cargo run --package
    #- run: cargo run --package
    - run: cargo run --package _09_shared_state
    - run: cargo run --package _10_fibonacci
    - run: cargo run --package _11_actor
    - run: cargo run --package _12_stack
    - run: cargo bench --package _13_bench
    #- run: cargo run --package
    #- run: cargo run --package
    #- run: cargo run --package
    #- run: cargo run --package
    #- run: cargo run --package
    #- run: cargo run --package
    #- run: cargo run --package
    #- run: cargo run --package
    #- run: cargo run --package
    #- run: cargo run --package
    #- run: cargo run --package
    #- run: cargo run --package
    #- run: cargo run --package
    #- run: cargo run --package
    #- run: cargo run --package
    #- run: cargo run --package
